export const PLANS = [
    {
        id: "free_diagnostico",
        name: "Diagnóstico",
        price: 0,
        currency: "CLP",
        recommended: false,
        features: [
            "Diagnóstico de CV con IA",
            "Detección de errores críticos",
            "Preview bloqueado de CV optimizado",
            "Estimación de oportunidades perdidas",
        ],
        limits: {
            cv: 0, // No generation
            export: 0,
            coverLetter: 0,
            tracker: 0,
        },
    },
    {
        id: "plan_a_impulso",
        name: "Impulso",
        price: 5990,
        currency: "CLP",
        recommended: false,
        stripePriceId: process.env.STRIPE_PRICE_PLAN_A,
        features: [
            "1 CV optimizado activo",
            "1 Carta de presentación",
            "ATS Scan completo",
            "5 Exportaciones PDF/DOCX",
            "Job Tracker (10 postulaciones)",
        ],
        limits: {
            cv: 1,
            export: 5,
            coverLetter: 1,
            tracker: 10,
        },
    },
    {
        id: "plan_b_aceleracion",
        name: "Aceleración",
        price: 10990,
        currency: "CLP",
        recommended: true,
        stripePriceId: process.env.STRIPE_PRICE_PLAN_B,
        features: [
            "CVs ilimitados",
            "Cartas ilimitadas",
            "Optimización por oferta laboral",
            "Tracker ilimitado",
            "Plantillas Premium",
            "Job Match Score",
        ],
        limits: {
            cv: Infinity,
            export: Infinity,
            coverLetter: Infinity,
            tracker: Infinity,
        },
    },
    {
        id: "plan_c_inevitable_pro",
        name: "Inevitable Pro",
        price: 21990,
        currency: "CLP",
        recommended: false,
        stripePriceId: process.env.STRIPE_PRICE_PLAN_C,
        features: [
            "Todo lo del Plan B",
            "Cambio de carrera asistido",
            "Logros automáticos",
            "Optimización salarial",
            "Soporte prioritario",
        ],
        limits: {
            cv: Infinity,
            export: Infinity,
            coverLetter: Infinity,
            tracker: Infinity,
        },
    },
];
